# -*- coding: utf-8 -*-
"""PROTOTIPO IBELT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XJTzxG76JD9EW6f-jmOYQqTql6BOZpCD

# Assistente PierX
"""

!pip install faiss-cpu
!pip install openai

import openai
import faiss
import os
from openai import OpenAI
import numpy as np
from google.colab import userdata

from transformers import AutoTokenizer, AutoModel
import torch

# Exemplo de perguntas e respostas fictícias
faq_data = [
    ("Como posso redefinir minha senha?", "Você pode redefinir sua senha clicando em 'Esqueci minha senha' na página de login."),
    ("Quais são os métodos de pagamento aceitos?", "Aceitamos cartões de crédito, PayPal e transferências bancárias."),
    ("Como posso entrar em contato com o suporte?", "Você pode entrar em contato com o suporte via e-mail ou chat ao vivo em nosso site."),
    ("Existe um aplicativo móvel disponível?", "Sim, nosso aplicativo móvel está disponível para iOS e Android."),
    ("Como faço para cancelar minha assinatura?", "Para cancelar sua assinatura, vá até 'Configurações' e clique em 'Cancelar assinatura'."),
    ("Quais são os benefícios de usar a plataforma?", "A plataforma oferece suporte especializado, simplificação de processos e maximização de incentivos fiscais para inovação."),
    ("Como a plataforma garante a segurança dos meus dados?", "Utilizamos criptografia avançada e seguimos rigorosos padrões de segurança para proteger seus dados."),
    ("A plataforma é compatível com quais navegadores?", "Nossa plataforma é compatível com os navegadores mais populares, incluindo Chrome, Firefox, Safari e Edge."),
    ("É possível integrar a plataforma com outros softwares?", "Sim, oferecemos integrações com diversos softwares de contabilidade e gestão de projetos."),
    ("Há um período de teste gratuito disponível?", "Sim, oferecemos um período de teste gratuito de 14 dias para novos usuários."),
    ("Quais tipos de projetos são elegíveis para incentivos fiscais?", "Projetos que envolvem pesquisa, desenvolvimento e inovação tecnológica são geralmente elegíveis."),
    ("A plataforma oferece suporte para empresas de todos os tamanhos?", "Sim, nossa plataforma é projetada para atender empresas de todos os tamanhos, desde startups até grandes corporações."),
    ("Como posso atualizar minhas informações de pagamento?", "Você pode atualizar suas informações de pagamento na seção 'Faturamento' do seu perfil."),
    ("Existe algum treinamento disponível para novos usuários?", "Sim, oferecemos webinars e tutoriais para ajudar novos usuários a se familiarizarem com a plataforma."),
    ("Como posso acompanhar o status do meu pedido de incentivo?", "Você pode acompanhar o status do seu pedido na seção 'Meus Pedidos' do seu painel de controle."),
    ("A plataforma está disponível em quais idiomas?", "Atualmente, nossa plataforma está disponível em português, inglês e espanhol."),
    ("Como posso adicionar novos membros da equipe à minha conta?", "Você pode adicionar novos membros da equipe na seção 'Equipe' do seu perfil."),
    ("Qual é o custo da assinatura mensal?", "Os preços variam de acordo com o plano escolhido. Consulte nossa página de preços para mais detalhes."),
    ("A plataforma oferece suporte em tempo real?", "Sim, oferecemos suporte em tempo real via chat durante o horário comercial."),
    ("Como posso enviar feedback sobre a plataforma?", "Você pode enviar seu feedback através do formulário de contato disponível em nosso site."),
    ("A plataforma ajuda a identificar oportunidades de incentivos fiscais?", "Sim, nossa plataforma possui ferramentas que ajudam a identificar e maximizar oportunidades de incentivos fiscais."),
    ("Quais são os requisitos para se qualificar para incentivos fiscais?", "Os requisitos podem variar, mas geralmente incluem a realização de atividades de P&D e inovação."),
    ("Como posso acessar relatórios de desempenho dos meus projetos?", "Relatórios de desempenho estão disponíveis na seção 'Relatórios' do seu painel de controle."),
    ("Existe algum custo adicional além da assinatura?", "Não, todos os custos estão incluídos na assinatura, a menos que você opte por serviços adicionais."),
    ("A plataforma oferece suporte para preenchimento de formulários de incentivo?", "Sim, nossa equipe pode ajudar no preenchimento e submissão de formulários de incentivo."),
    ("Como posso alterar meu plano de assinatura?", "Você pode alterar seu plano de assinatura na seção 'Plano' do seu perfil."),
    ("Os dados inseridos na plataforma são compartilhados com terceiros?", "Não, seus dados são confidenciais e não são compartilhados com terceiros sem seu consentimento."),
    ("A plataforma oferece alguma garantia de sucesso na obtenção de incentivos?", "Embora ofereçamos suporte e ferramentas para maximizar suas chances, não podemos garantir o sucesso devido a fatores externos."),
    ("Como posso participar de webinars e eventos da plataforma?", "Você pode se inscrever em webinars e eventos através da seção 'Eventos' do nosso site."),
    ("A plataforma oferece alguma certificação para usuários?", "Sim, oferecemos certificações após a conclusão de determinados treinamentos e cursos oferecidos pela plataforma.")
]

# tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
# model = AutoModel.from_pretrained("bert-base-uncased")

client = OpenAI(api_key = userdata.get('OPENAI_API_KEY'))

def criar_indice_faiss(faq_data):
    embeddings = np.array([obter_embedding_real(pergunta) for pergunta, _ in faq_data]).astype('float32')
    index = faiss.IndexFlatL2(embeddings.shape[1])
    index.add(embeddings)
    return index, embeddings

# def obter_embedding_real(texto):
#     inputs = tokenizer(texto, return_tensors="pt", truncation=True, padding=True, max_length=512)
#     with torch.no_grad():
#         outputs = model(**inputs)
#     # Usar a saída do token CLS como o embedding do texto
#     embedding = outputs.last_hidden_state[:, 0, :].squeeze().numpy()
#     return embedding

def obter_embedding_real(text):
    model="text-embedding-3-small"
    text = text.replace("\n", " ")
    embedding = client.embeddings.create(input = [text], model=model).data[0].embedding
    return embedding

def encontrar_resposta(pergunta, index, embeddings, faq_data):
    pergunta_embedding = obter_embedding_real(pergunta)
    _, indices = index.search(np.array([pergunta_embedding]), 1)
    return faq_data[indices[0][0]][1]

def quebra_linha(texto, x):
    palavras = texto.split()
    linhas = []
    for i in range(0, len(palavras), x):
        linha = ' '.join(palavras[i:i + x])
        linhas.append(linha)
    return '\n'.join(linhas)

# Criação do índice FAISS
index, embeddings = criar_indice_faiss(faq_data)

# Função para responder a perguntas
def responder_pergunta_com_historico(historico, pergunta, index, embeddings, faq_data):
    resposta_relevante = encontrar_resposta(pergunta, index, embeddings, faq_data)
    prompt = "\n".join([f"Usuário: {pergunta}\n", f"Conteúdo relevante para responder o usuário: {resposta_relevante}\n", "Reponda a pergunta com base no conteúdo relevante, mas pode complementar a resposta para deixar mais completa"])
    system_prompt = """
    Você é um assistente útil. Responda a pergunta de acordo com o último conteúdo da Resposta relevante.
    Avalie o conteúdo relevante, caso não ache coerente com a última pergunta, diga 'Não tenho informações suficientes para responder essa pergunta.'
    Responda apenas a última pergunta feita pelo usuário, ou seja, caso não faça sentido continuar o raciocínio da conversa, foque no último assunto abordado pelo usuário.
    Pode complementar a resposta com base no conteúdo relevante e adicionar algo a mais para deixar mais completo.
    Se comporte como um chatbot, irei enviar a pergunta do usuário e um conteúdo relevante para se basear, responda o que um atendente responderia.
    """
    try:
        resposta = client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {"role": "system", "content": system_prompt},
            ]+historico+[{"role": "user", "content": prompt}],
        )
        # Acessar o conteúdo da resposta corretamente
        resposta_texto = resposta.choices[0].message.content.strip()
        historico.append({"role": "user", "content": pergunta})
        historico.append({"role": "system", "content": resposta_texto})
        return [historico, resposta_texto]
    except Exception as e:
        return f"Erro ao obter resposta: {str(e)}"


# Inicializar o histórico
historico_conversa = []

"""# Chat"""

# Simulação de uma conversa
while True:
    pergunta = input("Usuário: ")
    if pergunta.lower() == "sair":
        break
    resp = responder_pergunta_com_historico(historico_conversa, pergunta, index, embeddings, faq_data)
    historico_conversa = resp[0]
    resposta = resp[1]
    print(100*"_")
    print(f"Assistente: {quebra_linha(resposta, 10)}")
    print(100*"_")